(defun day1 (filepath)
  (let ((sum 0))
	(with-open-file (stream filepath)
	  (do ((this (read stream nil) (read stream nil)))
		  ((not this) (print sum))
		(setf sum (+ sum (eval this)))))))

(defun day1-part2 (filepath sum results)
  (with-open-file (stream filepath)
	(do* ((this (read stream nil) (read stream nil))
		  )
		 ((not this) (return (day1-part2 filepath sum results)))
	  (setf sum (+ sum (eval this)))
	  (if (member sum results)
		  (return sum))
	  (setf results (cons sum results))
	  )))

;;(day1 filepath)
;;(day1-part2 filepath 0 '())
