[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tools = {path = "../2020/tools"}
hex = "0.4"

[profile.dev]
lto = true

[profile.dev.package."*"]
opt-level = 3
